#!/bin/python

first_name = 'Wayne'
last_name = 'Major'
age = '34'
birth_date = '03.23.1983'

print("My name is %s %s." % (first_name, last_name))
print("I was born on %s and I'm %s years old." % (birth_date, age))
